# Generated by Django 5.1.4 on 2025-04-10 10:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBuy',
            fields=[
                ('bulkBuyID', models.AutoField(primary_key=True, serialize=False)),
                ('bulkBuyNo', models.CharField(max_length=10)),
                ('bulkBuyDate', models.DateField(default=datetime.date.today)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkBuyDetails',
            fields=[
                ('bbdID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=20)),
                ('itemSpec', models.CharField(max_length=100)),
                ('itemPrice', models.FloatField()),
                ('itemQty', models.IntegerField()),
                ('bulkBuyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.bulkbuy')),
            ],
        ),
        migrations.CreateModel(
            name='BulkBuyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField(default=datetime.date.today)),
                ('response_status', models.BooleanField()),
                ('bbdID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.bulkbuydetails')),
                ('bulkBuyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.bulkbuy')),
                ('response_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
