# Generated by Django 5.1.4 on 2025-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0002_bulkbuy_bulkbuydetails_bulkbuyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuy',
            name='bulkBuyNo',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
