# Generated by Django 5.1.4 on 2025-05-02 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0003_alter_bulkbuy_bulkbuyno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('suborderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(default='Pending Order', max_length=25)),
                ('remark', models.CharField(default=None, max_length=20, null=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.order')),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='suborderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omsapp.suborder'),
        ),
    ]
