# Generated by Django 5.1.4 on 2025-05-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0005_alter_order_userid_alter_orderdetails_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='omsapp.item'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='omsapp.order'),
        ),
    ]
