# Generated by Django 5.1.4 on 2025-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0006_alter_orderdetails_itemid_alter_suborder_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbuy',
            name='bulkBuyExpDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bulkbuyresponse',
            name='response_remark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
