# Generated by Django 5.1.4 on 2025-05-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0007_bulkbuy_bulkbuyexpdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuydetails',
            name='bulkBuyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkbuyid_bbd', to='omsapp.bulkbuy'),
        ),
        migrations.AlterField(
            model_name='bulkbuyresponse',
            name='bulkBuyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkbuyid_bbr', to='omsapp.bulkbuy'),
        ),
    ]
