# Generated by Django 5.1.4 on 2025-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0008_alter_bulkbuydetails_bulkbuyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuy',
            name='bulkBuyNo',
            field=models.CharField(default='0000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNo',
            field=models.CharField(max_length=11),
        ),
    ]
