# Generated by Django 5.1.4 on 2025-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0009_alter_bulkbuy_bulkbuyno_alter_order_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbuydetails',
            name='itemUnit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
