# Generated by Django 5.1.4 on 2025-05-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0010_bulkbuydetails_itemunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkbuyresponse',
            name='bbdID',
        ),
        migrations.RemoveField(
            model_name='bulkbuyresponse',
            name='id',
        ),
        migrations.AddField(
            model_name='bulkbuyresponse',
            name='bbrID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BulkBuyResponseDetails',
            fields=[
                ('bbrdID', models.AutoField(primary_key=True, serialize=False)),
                ('itemPrice_indicative', models.FloatField()),
                ('itemPrice_response', models.FloatField()),
                ('itemQty_indicative', models.IntegerField(default=0)),
                ('itemQty_response', models.IntegerField(default=0)),
                ('bbdID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.bulkbuydetails')),
                ('bbrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsapp.bulkbuyresponse')),
            ],
        ),
    ]
