# Generated by Django 5.1.4 on 2025-05-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0011_remove_bulkbuyresponse_bbdid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuyresponsedetails',
            name='bbrID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkbuyid_bbrd', to='omsapp.bulkbuyresponse'),
        ),
    ]
