# Generated by Django 5.1.4 on 2025-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0013_bulkbuyresponse_response_remark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbuy',
            name='response_accept',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bulkbuyresponse',
            name='response_remark',
            field=models.CharField(default='Pending', max_length=250),
        ),
    ]
