# Generated by Django 5.1.4 on 2025-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0014_bulkbuy_response_accept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('', 'Select Usertype'), ('1', 'FPO'), ('2', 'Business'), ('3', 'Institution'), ('4', 'Overseas'), ('5', 'Individual')], max_length=20),
        ),
    ]
