# Generated by Django 5.1.4 on 2025-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0017_useraddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='setDefault',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
