# Generated by Django 5.1.4 on 2025-05-21 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0018_alter_useraddresses_setdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approvedOn',
            field=models.DateTimeField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userApproved',
            field=models.BooleanField(null=True),
        ),
    ]
