# Generated by Django 5.1.4 on 2025-05-21 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0019_customuser_approvedon_customuser_userapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuyresponse',
            name='response_remark_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='approvedOn',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='dateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
