# Generated by Django 5.1.4 on 2025-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0020_alter_bulkbuyresponse_response_remark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approvedOn',
            field=models.DateField(null=True),
        ),
    ]
