# Generated by Django 5.1.4 on 2025-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0021_alter_customuser_approvedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
    ]
