# Generated by Django 5.1.4 on 2025-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0022_customuser_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activatedOn',
            field=models.DateField(null=True),
        ),
    ]
