# Generated by Django 5.1.4 on 2025-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0024_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='orderNote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
