# Generated by Django 5.1.4 on 2025-05-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0025_order_ordernote_suborder_ordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
