# Generated by Django 5.1.4 on 2025-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0026_alter_item_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bill_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bill_address_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_address_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='address_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
