# Generated by Django 5.1.4 on 2025-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0027_customuser_bill_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fpo_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='FPODocs'),
        ),
    ]
