# Generated by Django 5.1.4 on 2025-06-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0028_customuser_fpo_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fpo_documents',
        ),
    ]
