# Generated by Django 5.1.4 on 2025-06-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0029_remove_customuser_fpo_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPOAuthorisationDocs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=100, null=True)),
                ('board_resolution', models.FileField(null=True, upload_to='fpodocs/', verbose_name='EXIM')),
                ('cin', models.FileField(null=True, upload_to='fpodocs/', verbose_name='CIN')),
                ('pan', models.FileField(null=True, upload_to='fpodocs/', verbose_name='PAN')),
                ('bank', models.FileField(null=True, upload_to='fpodocs/', verbose_name='Bank')),
                ('fssai', models.FileField(null=True, upload_to='fpodocs/', verbose_name='FSSAI')),
                ('gst', models.FileField(null=True, upload_to='fpodocs/', verbose_name='GST')),
                ('apmc', models.FileField(null=True, upload_to='fpodocs/', verbose_name='APMC')),
                ('exim', models.FileField(null=True, upload_to='fpodocs/', verbose_name='EXIM')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
