# Generated by Django 5.1.4 on 2025-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0030_fpoauthorisationdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='apmc',
            field=models.FileField(blank=True, null=True, upload_to='fpodocs/', verbose_name='APMC'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='exim',
            field=models.FileField(blank=True, null=True, upload_to='fpodocs/', verbose_name='EXIM'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='gst',
            field=models.FileField(blank=True, null=True, upload_to='fpodocs/', verbose_name='GST'),
        ),
    ]
