# Generated by Django 5.1.4 on 2025-06-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0031_alter_fpoauthorisationdocs_apmc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='apmc_remark',
            field=models.DateField(null=True, verbose_name='APMC Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='apmc_verified',
            field=models.BooleanField(null=True, verbose_name='APMC Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='apmc_verified_on',
            field=models.DateField(null=True, verbose_name='APMC Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='bank_remark',
            field=models.DateField(null=True, verbose_name='Bank Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='bank_verified',
            field=models.BooleanField(null=True, verbose_name='Bank Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='bank_verified_on',
            field=models.DateField(null=True, verbose_name='Bank Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='br_remark',
            field=models.DateField(null=True, verbose_name='Board Resolution Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='br_verified',
            field=models.BooleanField(null=True, verbose_name='Board Resolution Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='br_verified_on',
            field=models.DateField(null=True, verbose_name='Board Resolution Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='cin_remark',
            field=models.DateField(null=True, verbose_name='CIN Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='cin_verified',
            field=models.BooleanField(null=True, verbose_name='CIN Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='cin_verified_on',
            field=models.DateField(null=True, verbose_name='CIN Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='exim_remark',
            field=models.DateField(null=True, verbose_name='EXIM Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='exim_verified',
            field=models.BooleanField(null=True, verbose_name='EXIM Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='exim_verified_on',
            field=models.DateField(null=True, verbose_name='EXIM Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='fssai_remark',
            field=models.DateField(null=True, verbose_name='FSSAI Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='fssai_verified',
            field=models.BooleanField(null=True, verbose_name='FSSAI Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='fssai_verified_on',
            field=models.DateField(null=True, verbose_name='FSSAI Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='gst_remark',
            field=models.DateField(null=True, verbose_name='GST Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='gst_verified',
            field=models.BooleanField(null=True, verbose_name='GST Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='gst_verified_on',
            field=models.DateField(null=True, verbose_name='GST Verified On'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='pan_remark',
            field=models.DateField(null=True, verbose_name='PAN Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='pan_verified',
            field=models.BooleanField(null=True, verbose_name='PAN Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='pan_verified_on',
            field=models.DateField(null=True, verbose_name='PAN Verified On'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='board_resolution',
            field=models.FileField(null=True, upload_to='fpodocs/', verbose_name='Board Resolution'),
        ),
    ]
