# Generated by Django 5.1.4 on 2025-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0032_fpoauthorisationdocs_apmc_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='auth_contact',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='auth_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='auth_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
