# Generated by Django 5.1.4 on 2025-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0033_fpoauthorisationdocs_auth_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTransportation',
            field=models.FloatField(default=0),
        ),
    ]
