# Generated by Django 5.1.4 on 2025-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0034_order_ordertransportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='apmc_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='APMC Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='bank_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='Bank Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='br_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='Board Resolution Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='cin_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='CIN Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='exim_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='EXIM Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='fssai_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='FSSAI Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='gst_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='GST Remark'),
        ),
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='pan_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='PAN Remark'),
        ),
    ]
