# Generated by Django 5.1.4 on 2025-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0035_alter_fpoauthorisationdocs_apmc_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivateRemark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
