# Generated by Django 5.1.4 on 2025-06-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0037_suborder_paymentdate_suborder_paymentmode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='inviceID',
            new_name='invoiceID',
        ),
        migrations.AddField(
            model_name='invoice',
            name='suborderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omsapp.suborder'),
        ),
    ]
