# Generated by Django 5.1.4 on 2025-06-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0038_rename_inviceid_delivery_invoiceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='subOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omsapp.suborder'),
        ),
    ]
