# Generated by Django 5.1.4 on 2025-06-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0039_delivery_suborderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='subOrderID',
            new_name='suborderID',
        ),
    ]
