# Generated by Django 5.1.4 on 2025-06-10 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0040_rename_suborderid_delivery_suborderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='deliveryTime',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveryImg',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
