# Generated by Django 5.1.4 on 2025-06-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0041_remove_delivery_deliverytime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='invoiceID',
        ),
    ]
