# Generated by Django 5.1.4 on 2025-06-11 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0042_remove_delivery_invoiceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msgDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('email', models.CharField(max_length=100, verbose_name='Sender Email')),
                ('msg', models.CharField(max_length=500, verbose_name='Message')),
            ],
        ),
    ]
