# Generated by Django 5.1.4 on 2025-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0044_rename_useraddresses_usershippingaddresses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='OrderDelivery',
        ),
        migrations.RenameModel(
            old_name='Invoice',
            new_name='OrderInvoice',
        ),
    ]
