# Generated by Django 5.1.4 on 2025-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0045_rename_delivery_orderdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentRefNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
