# Generated by Django 5.1.4 on 2025-06-13 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0046_order_paymentdate_order_paymentmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbuy',
            name='bulkBuyDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bulkbuyresponse',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='deliveryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
