# Generated by Django 5.1.4 on 2025-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0047_alter_bulkbuy_bulkbuydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillingaddresses',
            name='contactNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='contactNo1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='contactPerson1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
