# Generated by Django 5.1.4 on 2025-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0048_userbillingaddresses_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contactNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contactNo1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contactPerson1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pinCode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pinCode1',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userAddress1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userCity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userCity1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userNote',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userState',
            field=models.CharField(choices=[('', 'Select State'), ('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chhattisgarh'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jharkhand'), ('11', 'Karnataka'), ('12', 'Kerala'), ('13', 'Madhya Pradesh'), ('14', 'Maharashtra'), ('15', 'Manipur'), ('16', 'Meghalaya'), ('17', 'Mizoram'), ('18', 'Nagaland'), ('19', 'Odisha'), ('20', 'Punjab'), ('21', 'Rajasthan'), ('22', 'Sikkim'), ('23', 'Tamil Nadu'), ('24', 'Telangana'), ('25', 'Tripura'), ('26', 'Uttar Pradesh'), ('27', 'Uttarakhand'), ('28', 'West Bengal'), ('29', 'Andaman and Nicobar Islands [UT]'), ('30', 'Chandigarh [UT]'), ('31', 'Dadra and Nagar Haveli and Daman and Diu [UT]'), ('32', 'Delhi [UT]'), ('33', 'Jammu and Kashmir [UT]'), ('34', 'Ladakh [UT]'), ('35', 'Lakshadweep [UT]'), ('36', 'Puducherry [UT]')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userState1',
            field=models.CharField(choices=[('', 'Select State'), ('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chhattisgarh'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jharkhand'), ('11', 'Karnataka'), ('12', 'Kerala'), ('13', 'Madhya Pradesh'), ('14', 'Maharashtra'), ('15', 'Manipur'), ('16', 'Meghalaya'), ('17', 'Mizoram'), ('18', 'Nagaland'), ('19', 'Odisha'), ('20', 'Punjab'), ('21', 'Rajasthan'), ('22', 'Sikkim'), ('23', 'Tamil Nadu'), ('24', 'Telangana'), ('25', 'Tripura'), ('26', 'Uttar Pradesh'), ('27', 'Uttarakhand'), ('28', 'West Bengal'), ('29', 'Andaman and Nicobar Islands [UT]'), ('30', 'Chandigarh [UT]'), ('31', 'Dadra and Nagar Haveli and Daman and Diu [UT]'), ('32', 'Delhi [UT]'), ('33', 'Jammu and Kashmir [UT]'), ('34', 'Ladakh [UT]'), ('35', 'Lakshadweep [UT]'), ('36', 'Puducherry [UT]')], max_length=20, null=True),
        ),
    ]
