# Generated by Django 5.1.4 on 2025-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0049_customuser_contactno_customuser_contactno1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sch_udise',
            field=models.CharField(blank=True, default='00000000000', max_length=11),
        ),
    ]
