# Generated by Django 5.1.4 on 2025-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0050_customuser_sch_udise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUDISE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('sub_dist_name', models.CharField(max_length=50)),
                ('village_name', models.CharField(max_length=50)),
                ('udise_code', models.CharField(max_length=11)),
                ('school_name', models.CharField(max_length=50)),
                ('school_cat', models.CharField(max_length=20)),
                ('school_type', models.CharField(max_length=20)),
                ('loc_lat', models.FloatField()),
                ('loc_long', models.FloatField()),
            ],
        ),
    ]
