# Generated by Django 5.1.4 on 2025-07-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0051_schooludise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sch_udise',
            new_name='udise_code',
        ),
    ]
