# Generated by Django 5.1.4 on 2025-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0053_fposervingaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='fposervingaddresses',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
