# Generated by Django 5.1.4 on 2025-07-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0054_fposervingaddresses_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userDistrict',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userDistrict1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userDistrict1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userDistrict',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userDistrict1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supply_place',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=70),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userState',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userState1',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fposervingaddresses',
            name='userState1',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userbillingaddresses',
            name='userState',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usershippingaddresses',
            name='userState1',
            field=models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20),
        ),
    ]
