# Generated by Django 5.1.4 on 2025-07-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0056_remove_customuser_contactno1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooludise',
            name='district_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='state_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='sub_dist_code',
            field=models.IntegerField(null=True),
        ),
    ]
