# Generated by Django 5.1.4 on 2025-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0057_schooludise_district_code_schooludise_state_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooludise',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
