# Generated by Django 5.1.4 on 2025-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0058_schooludise_total_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userCity1_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userDistrict1_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userState1_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userCity_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userDistrict_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userState_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userCity1_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userDistrict1_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userState1_code',
            field=models.IntegerField(null=True),
        ),
    ]
