# Generated by Django 5.1.4 on 2025-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0059_fposervingaddresses_usercity1_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userCity_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userDistrict_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userState_code',
            field=models.IntegerField(null=True),
        ),
    ]
