# Generated by Django 5.1.4 on 2025-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0060_customuser_usercity_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userCity_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userDistrict_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userState_code',
        ),
        migrations.RemoveField(
            model_name='fposervingaddresses',
            name='userCity1_code',
        ),
        migrations.RemoveField(
            model_name='fposervingaddresses',
            name='userDistrict1_code',
        ),
        migrations.RemoveField(
            model_name='fposervingaddresses',
            name='userState1_code',
        ),
        migrations.RemoveField(
            model_name='userbillingaddresses',
            name='userCity_code',
        ),
        migrations.RemoveField(
            model_name='userbillingaddresses',
            name='userDistrict_code',
        ),
        migrations.RemoveField(
            model_name='userbillingaddresses',
            name='userState_code',
        ),
        migrations.RemoveField(
            model_name='usershippingaddresses',
            name='userCity1_code',
        ),
        migrations.RemoveField(
            model_name='usershippingaddresses',
            name='userDistrict1_code',
        ),
        migrations.RemoveField(
            model_name='usershippingaddresses',
            name='userState1_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userCity_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userDistrict_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userState_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userCity1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userDistrict1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fposervingaddresses',
            name='userState1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userCity_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userDistrict_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbillingaddresses',
            name='userState_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userCity1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userDistrict1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddresses',
            name='userState1_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
