# Generated by Django 5.1.4 on 2025-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0061_remove_customuser_usercity_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='deliveryImg',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryimg/'),
        ),
    ]
