# Generated by Django 5.1.4 on 2025-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0062_orderdelivery_latitude_orderdelivery_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
