# Generated by Django 5.1.4 on 2025-08-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0063_alter_orderdelivery_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryCode', models.CharField(max_length=2, unique=True)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('categoryDesc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPincodeMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=6)),
                ('isActive', models.BooleanField(default=True)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pincode_map', to='omsapp.item')),
            ],
        ),
    ]
