# Generated by Django 5.1.4 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0064_itemcategory_itempincodemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooludise',
            name='class_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='class_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='i_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='ii_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='iii_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='iv_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='ix_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='pre_primary_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='total_students_with_preprimary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='v_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='vi_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='vii_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='viii_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='x_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='xi_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooludise',
            name='xii_students',
            field=models.IntegerField(default=0),
        ),
    ]
