# Generated by Django 5.1.4 on 2025-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0065_schooludise_class_from_schooludise_class_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='categoryCode',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
