# Generated by Django 5.1.4 on 2025-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0067_customuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
