# Generated by Django 5.1.4 on 2025-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0069_customuserotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserotp',
            name='otp_for',
            field=models.CharField(default='email', max_length=6),
        ),
    ]
