# Generated by Django 5.1.4 on 2025-08-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0070_customuserotp_otp_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserotp',
            old_name='user_id',   # your old field name
            new_name='userID',    # your new field name
        ),
    ]