# Generated by Django 5.1.4 on 2025-08-25 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0071_auto_20250825_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserotp',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuserotp',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
