# Generated by Django 5.1.4 on 2025-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0072_customuserotp_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='fssai',
            field=models.FileField(blank=True, null=True, upload_to='fpodocs/', verbose_name='FSSAI'),
        ),
    ]
