# Generated by Django 5.1.4 on 2025-08-25 16:51

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0073_alter_fpoauthorisationdocs_fssai'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('userType', models.CharField(choices=[('', 'Select Usertype'), ('1', 'FPO'), ('2', 'Business'), ('3', 'School'), ('4', 'Overseas'), ('5', 'Individual')], max_length=20)),
                ('udise_code', models.CharField(blank=True, default='00000000000', max_length=11)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('org_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('phone1', models.CharField(blank=True, default='', max_length=12)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('supply_place', models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=70)),
                ('gst_tmt', models.CharField(choices=[('', 'Select GST Treatment'), ('1', 'Registered Business (Regular)'), ('2', 'Registered Business (Composition)'), ('3', 'Unregistered Business'), ('4', 'Individual')], max_length=20)),
                ('contactPerson', models.CharField(blank=True, max_length=50, null=True)),
                ('contactNo', models.CharField(blank=True, max_length=15, null=True)),
                ('userAddress', models.CharField(max_length=200, null=True)),
                ('userCity', models.CharField(max_length=50, null=True)),
                ('userCity_name', models.CharField(max_length=50, null=True)),
                ('userState', models.CharField(choices=[('', 'Select State'), ('28', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('22', 'Chhattisgarh'), ('30', 'Goa'), ('24', 'Gujarat'), ('6', 'Haryana'), ('2', 'Himachal Pradesh'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('3', 'Punjab'), ('8', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('9', 'Uttar Pradesh'), ('5', 'Uttarakhand'), ('19', 'West Bengal'), ('35', 'Andaman And Nicobar Islands [UT]'), ('4', 'Chandigarh [UT]'), ('7', 'Delhi [UT]'), ('1', 'Jammu And Kashmir [UT]'), ('37', 'Ladakh [UT]'), ('31', 'Lakshadweep [UT]'), ('34', 'Puducherry [UT]'), ('38', 'The Dadra And Nagar Haveli And Daman And Diu [UT]')], max_length=20, null=True)),
                ('userState_name', models.CharField(max_length=50, null=True)),
                ('userDistrict', models.CharField(max_length=20, null=True)),
                ('userDistrict_name', models.CharField(max_length=50, null=True)),
                ('pinCode', models.CharField(max_length=6, null=True)),
                ('password', models.CharField(default='Admin@1234', max_length=20)),
                ('userApproved', models.BooleanField(null=True)),
                ('approvedOn', models.DateField(null=True)),
                ('isActive', models.BooleanField(null=True)),
                ('activatedOn', models.DateField(null=True)),
                ('deactivateRemark', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_address_lat', models.FloatField(blank=True, null=True)),
                ('bill_address_long', models.FloatField(blank=True, null=True)),
                ('ship_address_lat', models.FloatField(blank=True, null=True)),
                ('ship_address_long', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='omsapp.schooludise')),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
