# Generated by Django 5.1.4 on 2025-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0074_historicalcustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='change_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='change_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
