# Generated by Django 5.1.4 on 2025-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0075_customuser_change_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserotp',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
