# Generated by Django 5.1.4 on 2025-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0076_customuserotp_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserotp',
            name='otp_used_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
