# Generated by Django 5.1.4 on 2025-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0077_customuserotp_otp_used_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='ferli',
            field=models.FileField(blank=True, null=True, upload_to='fpodocs/', verbose_name='Fertiliser License'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='ferli_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='Fertiliser License Remark'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='ferli_verified',
            field=models.BooleanField(null=True, verbose_name='Fertiliser License Verified'),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='ferli_verified_on',
            field=models.DateField(null=True, verbose_name='Fertiliser License Verified On'),
        ),
    ]
