# Generated by Django 5.1.4 on 2025-09-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0079_alter_orderdelivery_suborderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='suborderID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdelivery', to='omsapp.suborder'),
        ),
    ]
