# Generated by Django 5.1.4 on 2025-09-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0080_alter_orderdelivery_suborderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbuy',
            name='order_frequency',
            field=models.CharField(default='Once', max_length=20),
        ),
    ]
