# Generated by Django 5.1.4 on 2025-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0081_bulkbuy_order_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
