# Generated by Django 5.1.4 on 2025-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0083_remove_login_email_remove_login_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
