# Generated by Django 5.1.4 on 2025-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0084_rename_username_login_userid_login_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='auth_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='fpo_pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fpoauthorisationdocs',
            name='fpo_regn_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
