# Generated by Django 5.1.4 on 2025-10-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0085_fpoauthorisationdocs_auth_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpoauthorisationdocs',
            name='fpo_pan',
        ),
    ]
