# Generated by Django 5.1.4 on 2025-10-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0086_remove_fpoauthorisationdocs_fpo_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
