# Generated by Django 5.1.4 on 2026-01-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0087_customuser_pan_historicalcustomuser_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpoauthorisationdocs',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_auth_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
