# Generated by Django 5.1.4 on 2026-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0088_alter_fpoauthorisationdocs_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='onefpo_itemID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
