# Generated by Django 5.1.4 on 2026-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0089_item_onefpo_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemImg',
            field=models.URLField(max_length=500, verbose_name='Image URL'),
        ),
    ]
