# Generated by Django 5.1.4 on 2026-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0090_alter_item_itemimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Unique Identifier of the Item'),
        ),
    ]
