# Generated by Django 5.1.4 on 2026-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0091_item_unique_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempincodemap',
            old_name='isActive',
            new_name='in_feature',
        ),
        migrations.RenameField(
            model_name='itempincodemap',
            old_name='itemID',
            new_name='item_id',
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
