# Generated by Django 5.1.4 on 2026-01-31 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0092_rename_isactive_itempincodemap_in_feature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempincodemap',
            old_name='id',
            new_name='item_pincode_map_id',
        ),
        migrations.RemoveField(
            model_name='itempincodemap',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itempincodemap',
            name='pincode',
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='cost_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='itemID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincode_maps', to='omsapp.item'),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='on_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='pinCode1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_pincode', to='omsapp.fposervingaddresses'),
        ),
        migrations.AddField(
            model_name='itempincodemap',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
