# Generated by Django 5.1.4 on 2026-01-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0093_rename_id_itempincodemap_item_pincode_map_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempincodemap',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_maps', to='omsapp.item'),
        ),
        migrations.AlterField(
            model_name='itempincodemap',
            name='pinCode1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pincode', to='omsapp.fposervingaddresses'),
        ),
    ]
