# Generated by Django 5.1.4 on 2026-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0094_alter_itempincodemap_itemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='sub_order_no',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gst_tmt',
            field=models.CharField(choices=[('', 'Select GST Treatment'), ('1', 'Registered Business (Regular)'), ('2', 'Registered Business (Composition)'), ('3', 'Unregistered Business'), ('4', 'Consumer/Individual'), ('5', 'SEZ Unit'), ('6', 'Deemed Export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='gst_tmt',
            field=models.CharField(choices=[('', 'Select GST Treatment'), ('1', 'Registered Business (Regular)'), ('2', 'Registered Business (Composition)'), ('3', 'Unregistered Business'), ('4', 'Consumer/Individual'), ('5', 'SEZ Unit'), ('6', 'Deemed Export')], max_length=20),
        ),
    ]
