# Generated by Django 5.1.4 on 2026-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0095_suborder_sub_order_no_alter_customuser_gst_tmt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='sub_order_no',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Suborder No.'),
        ),
    ]
