# Generated by Django 5.1.4 on 2026-02-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0096_alter_suborder_sub_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='sub_order_no',
            new_name='suborder_no',
        ),
    ]
