# Generated by Django 5.1.4 on 2026-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0097_rename_sub_order_no_suborder_suborder_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='suborder_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Suborder No.'),
        ),
    ]
