# Generated by Django 5.1.4 on 2026-02-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0098_alter_suborder_suborder_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
