# Generated by Django 5.1.4 on 2026-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0100_suborder_suborder_amount_suborder_suborder_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='itemGST',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='itemGSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='itemPricewithGST',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
