# Generated by Django 5.1.4 on 2026-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0101_alter_orderdetails_itemgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='deliveryImg',
            field=models.URLField(max_length=500, verbose_name='Delivery Image URL'),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='invoiceFile',
            field=models.URLField(max_length=500, verbose_name='Invoice URL'),
        ),
    ]
