# Generated by Django 5.1.4 on 2026-02-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0102_alter_orderdelivery_deliveryimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='suborderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdelivery', to='omsapp.suborder'),
        ),
    ]
