# Generated by Django 5.1.4 on 2026-02-21 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0103_alter_orderdelivery_suborderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='userID',
            new_name='customer_userID',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='inv_settle_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='invoice_settled',
            field=models.BooleanField(default=False),
        ),
    ]
