# Generated by Django 5.1.4 on 2026-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0104_rename_userid_orderinvoice_customer_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='deliveryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
