# Generated by Django 5.1.4 on 2026-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsapp', '0105_alter_orderdetails_deliverydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbuy',
            name='no_of_responses',
            field=models.IntegerField(default=0),
        ),
    ]
