from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
#region new UI urls
    path('', views.featured_product, name='index'),
    path('shop/', views.marketplace, name='shop'),
    path('shop/details/<str:item_id>',views.item_details, name='shopdetails'),
    path('cart/',views.cart_view, name='cart'),
    # path('fetch-district/<int:state_code>/',views.fetch_lgd_data_distrct, name='fetch-district'),
    # path('fetch-subdistrict/<str:state_code>/<str:district_code>',views.fetch_lgd_data_subdistrict, name='fetch-subdistrict'),
#endregion
    # path('', views.landing_page, name='index'),
    # path('home/', views.landing_page, name='index'),
    # path('home/cat/<str:category>', views.landing_page, name='index'),
    # path('shop', views.shop, name='shop'),
    # path('shop/cat/<str:category>', views.shop, name='shop-cat'),
    # path('shop/fpo/<str:fpo>', views.shop, name='shop-fpo'),
    # path('shop/zip/<str:region>', views.shop, name='shop-zip'),
    # path('shop/details/<str:item_id>',views.shop_details, name='shopdetails'),
    # path('shoppingcart', views.shopping_cart, name='shoppingcart'),
    path('checkout', views.checkout, name='checkout'),
    path('invoices/<int:order_id>', views.order_invoices, name='invoices'),

#region useful linkes
    path('contact', views.contact, name='contact'),
    path('blog', views.blog, name='blog'),
    path('about-us', views.aboutus, name='about-us'),
    path('privacy-policy', views.privacypolicy, name='privacy-policy'),
    path('delivery-policy', views.deliverypolicy, name='delivery-policy'),
    path('return-policy', views.returnpolicy, name='return-policy'),
    path('eula', views.eula, name='eula'),
    path('testimonials', views.testimonials, name='testimonials'),
#endregion

    path('bulk-buy', views.bulk_buy, name='bulk-buy'),
    path('bulk-buy/order', views.bulk_buy_order_place, name='bulk-buy-order'),
    path('bulk-buy/details/<int:bulk_order_id>', views.bulk_buy_order_details, name='bulk-buy-order-details'),
    path('bulk-buy/response/<int:bulkBuyID>/', views.bulk_buy_order_response, name='bulk-buy-order-response'),
    path('bulk-buy/response/details/<int:bulkBuyID>/<int:response_userID>', views.bulk_buy_order_response_details, name='bulk-buy-order-response-details'),
    path('bulk-buy-supply/', views.bulk_buy_supply, name='bulk-buy-supply'),
    path('bulk-buy-supply/<int:bulk_order_id>/', views.bulk_buy_details, name='bulk-buy-details'),
    path('bulk-buy-bid', views.bulk_buy_supply_bid, name='bulk-buy-bid'),
    path('bulk-buy-orders', views.bulk_buy_orders, name='bulk-buy-orders'),
    path('bulk-buy-response/', views.bulk_buy_response, name='bulk-buy-response'),
    path('bulk-buy-response/<int:bbr_id>/', views.bulk_buy_response_details, name='bulk-buy-response-details'),
    path('bulk-buy/response/accept/<int:bulkBuyID>/<int:response_userID>', views.bulk_buy_response_accept, name='bulk-buy-response-accept'),

    path('register/', views.registration_form, name='register'),
    path('register/user', views.register, name='register-user'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('resetpassword/', views.reset_password_form, name='resetpasswordform'),
    path('resetpassword/forget', views.reset_password_form, name='forgetpassword'),
    path('resetpassword/submit', views.reset_password, name='resetpassword'),
    path('admin-console/', views.admin_console, name='admin-console'),
    path('admin-master/', views.admin_master, name='admin-master'),
    path('approve-user/<int:userID>', views.approve_user, name='approve-user'),
    path('activate-user/<int:userID>/<str:activate>', views.activate_user, name='activate-user'),
    path('fetch-school/<str:udise>', views.fetch_school, name='fetch-school'),
    path('track-coordinate/', views.show_fpo_customers_in_map, name='track-coordinate'),
    path('change-phone/<str:new_phone>', views.change_mobile_number, name='change-phone'),

    path('user-form/', views.profile_view, name='user-form'),
    path('add-address/', views.add_address, name='add-address'),
    path('fetch-address/<int:id>', views.fetch_address, name='fetch-address'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('update-address/billing/<int:id>', views.update_billiing_address, name='update-billing'),
    path('update-address/shipping/<int:id>', views.update_shipping_address, name='update-shipping'),
    path('update-address/serving/<int:id>', views.update_serving_address, name='update-serving'),
    path('update-address/default/<int:id>', views.set_default_address, name='update-default-address'),
    path('update-serving-address/<int:id>', views.change_status_serving_address, name='update-serving-address'),

    path('accounts/login/', views.login_required, name='login'),
    path('items/', views.item_list, name='item_list'),
    path('item/entry/', views.item_entry, name='item_entry'),
    path('item/create/', views.create_item, name='create_item'),
    path('item/<int:item_id>/edit/', views.edit_item, name='edit_item'),
    path('item/<int:item_id>/change/', views.change_item_status, name='change_item_status'),
    path('item/<int:item_id>/stock/', views.item_stockout, name='change_item_stock'),
    path('item/<int:item_id>/feature/', views.item_feature, name='change_item_feature'),
    path('item/import', views.item_import, name='item_import'),

    path('cart/', views.cart_view, name='cart_view'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('error/', views.error_404_view, name='error'),
    path('search/', views.SearchItems, name='SearchItems'),
    path('search/results/', views.SearchItemView, name='SearchItemView'),
    path('createorder/<str:param_transportation_cost>/<str:param_total_price>/<str:param_gst_amount>/<str:param_deduction>', views.CreateOrder, name='createorder'),
    path('placedorders', views.PlacedOrders, name='orders'),
    path('placedorders/<int:orderID>/view', views.placed_order_details, name='orderdetails'),
    path('orderplace/',views.order_successful, name='order_successful'),
    path('billing/', views.register, name='billing'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/sellerprofile', views.seller_profile, name='sellerprofile'),
    path('profile/update/', views.register, name='profileedit'),
    path('profile/dashboard', views.dashboard, name='dashboard'),
    path('profile/auth/', views.fpo_auth, name='profile-auth'),
    path('profile/auth/save', views.upload_fpo_docs, name='profile-auth-save'),
    path('profile/verify/<int:userID>', views.verify_fpo, name='profile-verify'),
    
    path('revenue/', views.fpo_revenue, name='fpo-revenue'),
    path('customers/', views.fpo_customers, name='fpo-customers'),

    path('receivedorders/', views.ReceivedOrders, name='receivedorders'),
    path('invoicedorders/', views.invoiced_orders, name='invoicedorders'),
    path('confirm/<int:suborder_id>', views.confirm_delivery_order, name='confirmdelivery'),
    path('deliveredorders/', views.delivered_orders, name='deliveredorders'),
    path('rejectedorders/', views.rejected_orders, name='rejectedorders'),
    path('pendingorders/', views.pending_orders, name='pendingorders'),
    path('receivedorders/<int:orderID>/view', views.received_orders_details, name='receivedorderdetails'),
    path('receivedorders/<int:order_details_id>/accept', views.recived_order_status_update, name='acceptorder'),
    path('receivedorders/<int:order_details_id>/reject', views.recived_order_status_update, name='rejectorder'),
    path('receivedorders/<int:param_order_id>/acceptall', views.received_order_status_all, name='acceptall'),
    path('receivedorders/<int:param_order_id>/rejectall', views.received_order_status_all, name='rejectall'),
    path('uploadinvoice/<int:suborderID>', views.upload_invoice, name='uploadinvoice'),

    #"""Payment integration"""
    path('payment/', views.initiate_payment, name='initiate_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('webhook/', views.razorpay_webhook, name='razorpay_webhook'),

    #analytics
    path('analytics/<int:userID>/', views.user_analytics, name='analytics'),
    path('analytics/', views.user_analytics_items, name='analytics-items'),
]